pipeline:
  name: Build-Run
  identifier: BuildRun
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub_Connect
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Start Gatling Simulation
                  identifier: Start_Gatling_Simulation
                  spec:
                    connectorRef: Docker_Connector
                    image: maven:3.9.8-eclipse-temurin-17
                    shell: Sh
                    command: mvn gatling:enterpriseStart -Dgatling.enterprise.simulationName="Stress-Test-Harness"
                    envVariables:
                      GATLING_ENTERPRISE_API_TOKEN: <+secrets.getValue("GE_API_TOKEN")>
