pipeline:
  identifier: Build_karimatwa_Gatling_Harness_CI_1740058350957
  name: Build Gatling-Harness-CI
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: karimatwa/Gatling-Harness-CI
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Action
                  name: Setup JDK
                  identifier: Setup_JDK
                  spec:
                    uses: actions/setup-java@v3
                    with:
                      distribution: zulu
                      java-version: "17"
                      cache: maven
              - step:
                  type: Run
                  name: Build Package
                  identifier: Build_Package
                  spec:
                    shell: Sh
                    command: mvn gatling:enterpriseUpload -Dgatling.enterprise.simulationId=
                    envVariables:
                      GATLING_ENTERPRISE_API_TOKEN: <+secrets.getValue("GE_API_TOKEN")>
                      SIMULATION_ID: 330c7037-11bb-4a81-a5d4-11f9df770d93
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
